name: Build and Package Maven Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-jar
          path: target/*.jar